config/routes.rb
Rails.application.routes.draw do

  get 'contact', to: 'pages#contact'

  get 'hello', to: 'pages#welcome', as: :welcome

  get 'about', to: 'pages#about'

  get 'create', to: 'restaurants#create'

  root to: 'pages#home'

  resources :restaurants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def about
  end

  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    # if params[:food_type]
    #   @category = params[:food_type]
    #   @restaurants = Restaurant.select { |r| r[:category] == @category }
    # else
    #   @restaurants = RESTAURANTS
    # end
    @restaurants = Restaurant.all
  end

  def new
  end

  def create
    @restaurant = Restaurant.new(params[:restaurant])
    @restaurant.save

    redirect_to restaurant_path(@restaurant)
  end

  def show
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)

    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  def restaurant_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:restaurant).permit(:name, :address)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LacuillereTwo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>La Cuillere</h1>
    <%= yield %>
    <p>A very simple footer</p>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<form action="/restaurants" method="get">
  <input type="text" name="food_type" placeholder="What kind of food?">
  <input type="submit">
</form>

<form action="/restaurants" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name">
  <input type="text" name="address">
  <input type="submit">
</form>

app/views/pages/welcome.html.erb
<h1>hello :)</h1>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.submit %>
<% end %>

app/views/restaurants/create.html.erb
It was created!!! :)

app/views/restaurants/delete.html.erb
<%= link_to "Delete", restaurant_path(restaurant),
      method: :delete,
      data: { confirm: "Are you sure?" } %>

app/views/restaurants/edit.html.erb
  <h2><%= @restaurant.name %></h2>
  <p><%= @restaurant.address %></p>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<h2>Find lots of restaurants</h2>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
</ul>
<p><%= link_to "Know more about us", about_path %></p>
<p><%= link_to "Discover all our restaurants", restaurants_path %></p>
<p><%= link_to "Say hi", welcome_path %></p>

app/views/restaurants/new.html.erb
<form action="create" method="get">
  <label for="name">Name: </label>
  <input type="text" name="restaurant[:name]" id="name">

  <label for="address">Address: </label>
  <input type="text" name="restaurant[address]" id="address">

  <input type="submit">
</form>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p>Stars: <%= @restaurant.stars %></p>
<p><%= @restaurant.address %></p>

app/views/restaurants/update.html.erb
<h1>hello again :)</h1>